#!/bin/bash

echo "🚀 FPL Analytics Pro - GitHub Upload Script"
echo "==========================================="
echo ""
echo "1. First, create a new repository on GitHub:"
echo "   Go to: https://github.com/new"
echo "   Name: fpl-analytics-pro"
echo "   Description: ⚽ Fantasy Premier League Analytics Dashboard"
echo "   Set to: Public"
echo "   DON'T check 'Add a README file'"
echo ""
echo "2. After creating the repository, GitHub will show you commands."
echo "   Copy the remote URL and run:"
echo ""
echo "   git remote add origin https://github.com/YOURUSERNAME/fpl-analytics-pro.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. Replace 'YOURUSERNAME' with your actual GitHub username"
echo ""
echo "📂 Your project is ready in: $(pwd)"
echo "📊 Ready to upload: $(git log --oneline | wc -l | tr -d ' ') commit with $(git ls-files | wc -l | tr -d ' ') files"
echo ""
echo "🎉 After upload, your dashboard will be live for the FPL community!"
echo ""
echo "📱 To run locally: streamlit run enhanced_dashboard.py"